"""A deterministic, template-based report built directly from the same evidence the tools serve —
no LLM call. This is the default path (no ``ANTHROPIC_API_KEY``) and the only one verified
end-to-end without a live key; the tool-use loop in ``client.py`` falls back to it whenever the
live call is unavailable, refuses to end, or fails.
"""

from __future__ import annotations

from sentinel_core.taxonomy import Verdict

from .case import Case
from .report import Report

_ACTION: dict[Verdict, str] = {
    Verdict.CYBERATTACK: (
        "Escalate to the security team; preserve packet and command logs for this window."
    ),
    Verdict.MECHANICAL_FAILURE: "Route to the subsystem owner for a health check.",
    Verdict.ENVIRONMENTAL: (
        "Cross-check against the space-weather context; likely no action beyond logging."
    ),
    Verdict.SENSOR_MALFUNCTION: "Flag the sensor for recalibration or a redundancy failover.",
    Verdict.NOMINAL: "No action.",
    Verdict.NEEDS_HUMAN: (
        "Route to a human analyst; the model could not separate the top hypotheses."
    ),
}


def investigate_offline(case: Case) -> Report:
    s, ev = case.summary, case.evidence
    verdict = Verdict(s.verdict)

    key_evidence = [
        f"{c.feature}={c.value:.3g} contributed +{c.contribution:.3g} toward {verdict.value}"
        for c in ev.evidence_for[:3]
    ] or ["No feature contributed positively toward any class above the abstention threshold."]

    reasoning = [
        f"Attribution model {s.model_version} placed posterior "
        f"{s.posterior.get(verdict.value, 0.0):.2f} on {verdict.value}"
        + (f", runner-up {ev.runner_up}." if ev.runner_up else ".")
    ]
    pi = case.packet_integrity
    if pi.auth_failures or pi.commands_out_of_contact or pi.auth_failures_side:
        reasoning.append(
            f"Packet integrity: {pi.auth_failures} auth failures, "
            f"{pi.commands_out_of_contact} commands outside a contact window, "
            f"{pi.auth_failures_side} failed authentication events."
        )
    if case.space_weather:
        reasoning.append(
            f"{len(case.space_weather)} cached space-weather event(s) overlap this window."
        )
    if case.related:
        reasoning.append(
            f"{len(case.related)} other incident(s) in the same session may be related."
        )

    caveats = [
        "Generated by the deterministic offline fallback, not the Claude tool-use agent "
        "(no ANTHROPIC_API_KEY configured, or the live call did not complete)."
    ]
    if verdict == Verdict.NEEDS_HUMAN:
        caveats.append(
            "The attribution model itself abstained; this report cannot resolve that for you."
        )

    return Report(
        verdict=verdict,
        confidence=s.confidence,
        summary=(
            f"Incident {s.id} on session {s.session_id}: verdict {verdict.value} "
            f"(confidence {s.confidence:.2f}, severity {s.severity}) affecting "
            f"{', '.join(s.affected_channels) or 'no channel in particular'}."
        ),
        key_evidence=key_evidence,
        reasoning=reasoning,
        recommended_action=_ACTION[verdict],
        caveats=caveats,
    )
