"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-21 19:45:19.903143

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ---------------------------------------------------------------------------------------------
# TimescaleDB (PostgreSQL only; ADR 0007). On SQLite these tables stay ordinary tables. Verified
# only in CI against a TimescaleDB service (the dev machine has no Docker or Postgres).
HYPERTABLES = ("telemetry", "packets", "malformed_frames", "link_metrics", "detector_outputs")
CHUNK_INTERVAL = "1 day"
COMPRESS_AFTER = "7 days"
RETAIN_FOR = "30 days"  # demo retention; raise for real deployments


def _timescale() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    available = bind.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'timescaledb'")
    ).scalar()
    if not available:
        print("timescaledb extension not available: keeping plain PostgreSQL tables")
        return
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    for table in HYPERTABLES:
        op.execute(
            f"SELECT create_hypertable('{table}', 'ts', "
            f"chunk_time_interval => INTERVAL '{CHUNK_INTERVAL}', if_not_exists => TRUE, "
            "migrate_data => TRUE)"
        )
        op.execute(
            f"ALTER TABLE {table} SET "
            "(timescaledb.compress, timescaledb.compress_segmentby = 'session_id')"
        )
        op.execute(f"SELECT add_compression_policy('{table}', INTERVAL '{COMPRESS_AFTER}')")
        op.execute(f"SELECT add_retention_policy('{table}', INTERVAL '{RETAIN_FOR}')")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=254), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("family", sa.String(length=16), nullable=False),
        sa.Column("subsystem_group", sa.String(length=16), nullable=False),
        sa.Column("group_is_synthetic_grouping", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channels")),
    )
    op.create_table(
        "donki_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=4), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_donki_events")),
    )
    with op.batch_alter_table("donki_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_donki_events_event_time"), ["event_time"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_donki_events_kind"), ["kind"], unique=False)

    op.create_table(
        "eval_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("git_sha", sa.String(length=40), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("profile", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_runs")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("step_seconds", sa.Float(), nullable=False),
        sa.Column("speed", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "auth_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_auth_events_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_events")),
    )
    with op.batch_alter_table("auth_events", schema=None) as batch_op:
        batch_op.create_index("ix_auth_events_session_ts", ["session_id", "ts"], unique=False)

    op.create_table(
        "command_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opcode", sa.Integer(), nullable=False),
        sa.Column("opcode_name", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("auth_ok", sa.Boolean(), nullable=False),
        sa.Column("in_contact_window", sa.Boolean(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_command_log_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_command_log")),
    )
    with op.batch_alter_table("command_log", schema=None) as batch_op:
        batch_op.create_index("ix_command_log_session_ts", ["session_id", "ts"], unique=False)

    op.create_table(
        "detector_outputs",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("detector", sa.String(length=48), nullable=False),
        sa.Column("layer", sa.String(length=4), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("fired", sa.Boolean(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_detector_outputs_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", "ts", "n", name=op.f("pk_detector_outputs")),
    )
    op.create_table(
        "ground_truth",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("scenario_id", sa.String(length=64), nullable=False),
        sa.Column("class", sa.String(length=24), nullable=False),
        sa.Column("subtype", sa.String(length=48), nullable=False),
        sa.Column("start_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_ground_truth_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_ground_truth")),
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=12), nullable=False),
        sa.Column("posterior", sa.JSON(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("top_evidence", sa.JSON(), nullable=False),
        sa.Column("affected_channels", sa.JSON(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_incidents_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incidents_session_id"), ["session_id"], unique=False)

    op.create_table(
        "link_metrics",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("snr_db", sa.Float(), nullable=False),
        sa.Column("ber", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("loss_pct", sa.Float(), nullable=False),
        sa.Column("rx_pps", sa.Float(), nullable=False),
        sa.Column("queue_depth", sa.Integer(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_link_metrics_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", "ts", name=op.f("pk_link_metrics")),
    )
    op.create_table(
        "malformed_frames",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_malformed_frames_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", "ts", "n", name=op.f("pk_malformed_frames")),
    )
    op.create_table(
        "packets",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("apid", sa.Integer(), nullable=False),
        sa.Column("seq_count", sa.Integer(), nullable=False),
        sa.Column("ts_pkt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=4), nullable=False),
        sa.Column("auth_ok", sa.Boolean(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_packets_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", "ts", "n", name=op.f("pk_packets")),
    )
    op.create_table(
        "telemetry",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=32), nullable=False),
        sa.Column("ts_pkt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("cmd_mask", sa.BigInteger(), nullable=False),
        sa.Column("auth_ok", sa.Boolean(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"], ["channels.id"], name=op.f("fk_telemetry_channel_id_channels")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_telemetry_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", "ts", "n", name=op.f("pk_telemetry")),
    )
    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.create_index(
            "ix_telemetry_session_channel_ts", ["session_id", "channel_id", "ts"], unique=False
        )

    op.create_table(
        "investigation_events",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_investigation_events_incident_id_incidents"),
        ),
        sa.PrimaryKeyConstraint("incident_id", "seq", name=op.f("pk_investigation_events")),
    )
    op.create_table(
        "reports",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=8), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("markdown", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_reports_incident_id_incidents")
        ),
        sa.PrimaryKeyConstraint("incident_id", name=op.f("pk_reports")),
    )
    # ### end Alembic commands ###
    _timescale()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reports")
    op.drop_table("investigation_events")
    with op.batch_alter_table("telemetry", schema=None) as batch_op:
        batch_op.drop_index("ix_telemetry_session_channel_ts")

    op.drop_table("telemetry")
    op.drop_table("packets")
    op.drop_table("malformed_frames")
    op.drop_table("link_metrics")
    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incidents_session_id"))

    op.drop_table("incidents")
    op.drop_table("ground_truth")
    op.drop_table("detector_outputs")
    with op.batch_alter_table("command_log", schema=None) as batch_op:
        batch_op.drop_index("ix_command_log_session_ts")

    op.drop_table("command_log")
    with op.batch_alter_table("auth_events", schema=None) as batch_op:
        batch_op.drop_index("ix_auth_events_session_ts")

    op.drop_table("auth_events")
    op.drop_table("users")
    op.drop_table("sessions")
    op.drop_table("eval_runs")
    with op.batch_alter_table("donki_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_donki_events_kind"))
        batch_op.drop_index(batch_op.f("ix_donki_events_event_time"))

    op.drop_table("donki_events")
    op.drop_table("channels")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
